language: c
os: linux
sudo: required
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake libgmp3-dev gengetopt
    libpcap-dev flex byacc libjson-c-dev pkg-config libunistring-dev
    libsasl2-dev python-dev python-pip libhiredis-dev
  - pip install --user sh
  - python ./scripts/install_mongo.py
  - export PATH=/opt/bin:$PATH
matrix: 
  include:
    - os: osx
      before_install:
        - brew update
        - brew install gengetopt byacc libdnet libunistring
          mongo-c hiredis
script: 
  - cmake -DENABLE_DEVELOPMENT=ON -DWITH_REDIS=ON -DWITH_MONGO=ON
  - make
  - python ./scripts/check_manfile.py
compiler: clang
notifications:
  email:
  - zmap-devel@umich.edu
  slack:
    secure: gLiX4zUhlYMJ0l7kJlb5Wf5CmAynj+WQufThSBPP7XlLZddl6Vql72sJuqwl1ZV75xEsqP05QDulBMJc9AaED7BP53vhngHHgWLwjt026ne5sbA/s98U735jT/qwwFvKWBCYPZ5BQdTmJO3KCyuBJH+tQnptiolog9abksG1WZk=
